import { describe, expect, it } from "vitest"
import { checkArtifactsFresh, isExampleInstalled, runExampleStart } from "./support.js"

/**
 * application (examples/application) is the first of env-cap's three
 * flagship examples -- "how does this make my code better?" for an
 * individual developer. It demonstrates the simplest possible starting
 * point: one centralized `createEnv()` contract for a whole small app, no
 * capability-per-file ownership required, generated by calling the `env-cap`
 * CLI straight from a `docs` npm script with no wrapper script at all.
 *
 * This file verifies:
 *  - fail-fast `validateEnv()` startup against the real, committed `.env`
 *  - the committed generated output (manifest, docs/ENVIRONMENT.md,
 *    docs/OWNERSHIP.md, docs/env.evidence.json, .env.example) is exactly
 *    what a fresh run produces -- asserted through the example's own
 *    `check` script, against its real committed files, with no `expected/`
 *    mirror tree. See `support.ts`.
 */
const EXAMPLE = "application"
const installed = isExampleInstalled(EXAMPLE)

// Every test here shells out to a real npm script, which spawns its own Node
// process -- Vitest's 5s default assumes an in-process unit test.
const SUBPROCESS_TIMEOUT_MS = 30_000

describe(`example: ${EXAMPLE}`, () => {
  it.skipIf(!installed)(
    "validates and prints the resolved centralized contract",
    () => {
      const stdout = runExampleStart(EXAMPLE)
      expect(stdout).toContain("Environment validated successfully.")
      expect(stdout).toContain("Connecting to database on port 5432...")
      expect(stdout).toContain("Payment provider: stripe")
      expect(stdout).toContain("Log level: info")
    },
    SUBPROCESS_TIMEOUT_MS,
  )

  it.skipIf(!installed)(
    "has committed generated output matching a fresh generation",
    () => {
      checkArtifactsFresh(EXAMPLE)
    },
    SUBPROCESS_TIMEOUT_MS,
  )
})
