import fs from "node:fs/promises"
import path from "node:path"
import { describe, expect, it } from "vitest"
import { runExpectingFailure } from "../support/example-runner.js"
import {
  checkArtifactsFresh,
  exampleDir,
  isExampleInstalled,
  runExampleScript,
  runExampleStart,
} from "./support.js"

/**
 * team-service (examples/team-service) is the second of env-cap's three
 * flagship examples -- "how does this help my team?" for an engineering team
 * running a real service. Two mutually-exclusive database backends
 * (`postgres` active, `mongodb` inactive) gated by `exclusiveGroup` (ADR
 * 0009), plus `prisma`, an always-active third contract, and a fourth
 * capability `auth` owned by a different team (`security-team`, not
 * `data-platform-team`) carrying a `sensitivity: "secret"` variable -- so the
 * generated ownership matrix and security review have real, multi-team
 * content. Generated by calling the `env-cap` CLI straight from a `docs` npm
 * script, with no wrapper script.
 *
 * This file verifies:
 *  - `validateEnv()` succeeds with postgres active, mongodb excluded from
 *    the generated manifest entirely, and auth's secret loaded
 *  - the committed generated output matches a fresh generation, asserted
 *    against the real committed files with no `expected/` mirror tree
 *  - `check` (`--check`, the documented CI gate) reports drift, and writes
 *    nothing, once a source schema changes underneath it
 */
const EXAMPLE = "team-service"
const installed = isExampleInstalled(EXAMPLE)

const SUBPROCESS_TIMEOUT_MS = 30_000

describe(`example: ${EXAMPLE}`, () => {
  it.skipIf(!installed)(
    "validates with postgres active, mongodb excluded, and auth's secret loaded",
    () => {
      const stdout = runExampleStart(EXAMPLE)
      expect(stdout).toContain("Environment validated successfully.")
      expect(stdout).toContain("Prisma provider: postgresql")
      expect(stdout).toContain("Database URL: postgres://postgres:postgres@localhost:5432/app")
      expect(stdout).toContain("Session secret configured: true")
    },
    SUBPROCESS_TIMEOUT_MS,
  )

  it.skipIf(!installed)(
    "has committed generated output matching a fresh generation",
    () => {
      checkArtifactsFresh(EXAMPLE)
    },
    SUBPROCESS_TIMEOUT_MS,
  )

  it.skipIf(!installed)(
    "check (--check) fails without writing anything once a schema doc changes underneath it",
    async () => {
      const schemaPath = path.join(exampleDir(EXAMPLE), "features/auth/env.schema.ts")
      const original = await fs.readFile(schemaPath, "utf8")
      try {
        await fs.writeFile(
          schemaPath,
          original.replace(
            "Signs and verifies user session cookies.",
            "Signs and verifies user session cookies (rotated quarterly).",
          ),
          "utf8",
        )
        const output = runExpectingFailure(exampleDir(EXAMPLE), "check")
        expect(output).toContain("stale")
      } finally {
        // Restore before regenerating, so a failure here can never leave the
        // committed artifacts describing the mutated schema.
        await fs.writeFile(schemaPath, original, "utf8")
        runExampleScript(EXAMPLE, "docs")
      }
    },
    SUBPROCESS_TIMEOUT_MS,
  )
})
